services:
  web:
    build:
      context: .
      args:
        ENVIRONMENT: production
    ports:
      - "9999:9999"
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URL}