name: Test Coveralls
on: ["push", "pull_request"]
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: Run tests with coverage
        run: |
          pipenv run coverage run --source=. -m pytest
      - name: Coveralls report
        uses: coverallsapp/github-action@master
